# Generated by Django 3.2.9 on 2021-11-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('surname', models.CharField(max_length=200, verbose_name='Surname')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('company', models.CharField(choices=[('epam', 'EPAM'), ('google', 'Google'), ('apple', 'Apple')], max_length=100)),
                ('salary', models.IntegerField(verbose_name='Salary')),
            ],
        ),
    ]
